CREATE DATABASE Universidade;

USE Universidade;
GO

CREATE TABLE ALUNOS
(
    MATRICULA INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);
GO

CREATE TABLE CURSOS
(
    CURSO CHAR(3) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);
GO

CREATE TABLE PROFESSOR
(
    PROFESSOR INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);
GO

CREATE TABLE MATERIAS
(
    SIGLA CHAR(3) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARGAHORARIA INT NOT NULL,
    CURSO CHAR(3) NOT NULL,
    PROFESSOR INT NOT NULL,

    CONSTRAINT FK_MAT_CURSO
        FOREIGN KEY (CURSO) REFERENCES CURSOS(CURSO),

    CONSTRAINT FK_MAT_PROF
        FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR(PROFESSOR)
);
GO


CREATE TABLE MATRICULA
(
    ID_MATRICULA INT IDENTITY(1,1) PRIMARY KEY,

    ID_ALUNO INT NOT NULL,
    ID_MATERIA CHAR(3) NOT NULL,
    PERLETIVO INT NOT NULL,

    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(MATRICULA),
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS(SIGLA),

    UNIQUE (ID_ALUNO, ID_MATERIA, PERLETIVO)
);
GO


CREATE TABLE AVALIACOES
(
    ID_AVALIACAO INT IDENTITY(1,1) PRIMARY KEY,
    ID_MATRICULA INT NOT NULL,

    TIPO VARCHAR(20) NOT NULL, 
    NOTA DECIMAL(5,2) NOT NULL,

    CONSTRAINT FK_AVAL_MATR FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULA(ID_MATRICULA)
);
GO

CREATE TABLE FREQUENCIA
(
    ID_FREQUENCIA INT IDENTITY(1,1) PRIMARY KEY,
    ID_MATRICULA INT NOT NULL,

    DATA_AULA DATE NOT NULL,
    PRESENCA BIT NOT NULL,

    CONSTRAINT FK_FREQ_MATR FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULA(ID_MATRICULA)
);
GO

INSERT INTO ALUNOS (NOME) VALUES ('Pedro'), ('Maria');

INSERT INTO CURSOS (CURSO, NOME) VALUES ('ENG', 'ENGENHARIA'), ('ADM', 'ADMINISTRAÇÃO');

INSERT INTO PROFESSOR (NOME) VALUES ('Dornel'), ('Walter');

INSERT INTO MATERIAS (SIGLA, NOME, CARGAHORARIA, CURSO, PROFESSOR) 
VALUES ('BDA', 'BANCO DE DADOS', 144, 'ENG', 1), ('PRG', 'PROGRAMAÇÃO', 144, 'ENG', 2);

INSERT INTO MATRICULA (ID_ALUNO, ID_MATERIA, PERLETIVO) VALUES  (1, 'BDA', 2024), (1, 'PRG', 2024), (2, 'BDA', 2024);

INSERT INTO AVALIACOES (ID_MATRICULA, TIPO, NOTA) 
VALUES (1, 'N1', 8.5), (1, 'N2', 7.0),  (2, 'N1', 9.0), (2, 'N2', 8.5),  (3, 'N1', 6.0), (3, 'N2', 5.5);

INSERT INTO FREQUENCIA (ID_MATRICULA, DATA_AULA, PRESENCA) 
VALUES (1, '2024-03-01', 1), (1, '2024-03-02', 0),  (2, '2024-03-01', 1), (2, '2024-03-02', 1),  (3, '2024-03-01', 0), (3, '2024-03-02', 0);

/*
CREATE VIEW VIEW_FREQUENCIA AS
SELECT 
    ALUNO.NOME AS ALUNO,
    MATERIA.NOME AS MATERIA,
    FREQUENCIA.DATA_AULA,
    CASE 
        WHEN FREQUENCIA.PRESENCA = 1 THEN 'Presente'
        ELSE 'Falta'
    END AS STATUS
FROM FREQUENCIA
JOIN MATRICULA ON FREQUENCIA.ID_MATRICULA = MATRICULA.ID_MATRICULA
JOIN ALUNOS AS ALUNO ON MATRICULA.ID_ALUNO = ALUNO.MATRICULA
JOIN MATERIAS AS MATERIA ON MATRICULA.ID_MATERIA = MATERIA.SIGLA;
GO */ 


/*  VIEW CRIADO PARA VER A FREQUENCIA  */
SELECT * FROM VIEW_FREQUENCIA;


/*  MEDIA */
SELECT 
    ALUNO.NOME AS ALUNO,
    MATERIA.NOME AS MATERIA,

    CAST(
        ROUND(AVG(AVALIACOES.NOTA), 2)
    AS DECIMAL(5,2)) AS MEDIA

FROM AVALIACOES
JOIN MATRICULA ON AVALIACOES.ID_MATRICULA = MATRICULA.ID_MATRICULA
JOIN ALUNOS AS ALUNO ON MATRICULA.ID_ALUNO = ALUNO.MATRICULA
JOIN MATERIAS AS MATERIA ON MATRICULA.ID_MATERIA = MATERIA.SIGLA

GROUP BY ALUNO.NOME, MATERIA.NOME;

/* PORCENTAGEM DA FREQUENCIA */
SELECT 
    ALUNO.NOME AS ALUNO,
    MATERIA.NOME AS MATERIA,
    
    CAST(
        ROUND(
        SUM(CASE WHEN FREQUENCIA.PRESENCA = 1 THEN 1 ELSE 0 END) * 100.0 
        / NULLIF(COUNT(FREQUENCIA.ID_FREQUENCIA), 0)
    , 2) AS DECIMAL(5 , 2)) AS FREQUENCIAL_PERCENTUAL  

FROM FREQUENCIA
JOIN MATRICULA ON FREQUENCIA.ID_MATRICULA = MATRICULA.ID_MATRICULA
JOIN ALUNOS AS ALUNO ON MATRICULA.ID_ALUNO = ALUNO.MATRICULA
JOIN MATERIAS AS MATERIA ON MATRICULA.ID_MATERIA = MATERIA.SIGLA
GROUP BY ALUNO.NOME, MATERIA.NOME;


/* VIEW CRIADO PARA BOLETIM */

/*
USE Universidade;
GO

CREATE VIEW VIEW_BOLETIM AS
SELECT 
    ALUNO.NOME AS ALUNO,
    MATERIA.NOME AS MATERIA,

    /* MEDIA */
    CAST(ROUND(AVG(AVALIACOES.NOTA), 2) AS DECIMAL(5,2)) AS MEDIA,

    /* FREQUENCIA */
    CAST(
        ROUND(
            SUM(CASE WHEN FREQUENCIA.PRESENCA = 1 THEN 1 ELSE 0 END) * 100.0 
            / NULLIF(COUNT(FREQUENCIA.ID_FREQUENCIA), 0)
        , 2)
    AS DECIMAL(5,2)) AS FREQUENCIA,

    /* RESULTADO */
    CASE 
        WHEN 
            AVG(AVALIACOES.NOTA) >= 7
            AND 
            (SUM(CASE WHEN FREQUENCIA.PRESENCA = 1 THEN 1 ELSE 0 END) * 100.0 
             / NULLIF(COUNT(FREQUENCIA.ID_FREQUENCIA), 0)) >= 75
        THEN 'APROVADO'

        WHEN 
            AVG(AVALIACOES.NOTA) >= 5
            AND AVG(AVALIACOES.NOTA) < 7
            AND 
            (SUM(CASE WHEN FREQUENCIA.PRESENCA = 1 THEN 1 ELSE 0 END) * 100.0 
             / NULLIF(COUNT(FREQUENCIA.ID_FREQUENCIA), 0)) >= 75
        THEN 'EXAME'

        ELSE 'REPROVADO'
    END AS RESULTADO

FROM MATRICULA
JOIN ALUNOS AS ALUNO ON MATRICULA.ID_ALUNO = ALUNO.MATRICULA
JOIN MATERIAS AS MATERIA ON MATRICULA.ID_MATERIA = MATERIA.SIGLA
LEFT JOIN AVALIACOES ON AVALIACOES.ID_MATRICULA = MATRICULA.ID_MATRICULA
LEFT JOIN FREQUENCIA ON FREQUENCIA.ID_MATRICULA = MATRICULA.ID_MATRICULA

GROUP BY ALUNO.NOME, MATERIA.NOME;
GO */

SELECT * FROM VIEW_BOLETIM;
